/**
 * agentsync export — generate a standalone install.sh script that sets up
 * agent configs without requiring agentsync to be installed.
 *
 * Reads the current agentsync.json manifest and mcp.json, transforms MCP
 * configs for each enabled agent, and outputs a self-contained bash script.
 */

import * as fs from "node:fs";
import path from "node:path";
import os from "node:os";
import * as TOML from "smol-toml";
import { parseMCPConfig } from "../mcp/parser.js";
import { transformForAgent } from "../mcp/transformer.js";
import { loadAgentById } from "../core/schema-loader.js";
import { getPortableItems } from "../core/linker.js";
import { loadManifest } from "../utils/manifest.js";
import { expandPath, getPlatformPath } from "../utils/paths.js";
import { error, warn } from "../utils/output.js";
import type { AgentDefinition } from "../schemas/agent-schema.js";

export interface AgentExportInfo {
  agentDef: AgentDefinition;
  configDir: string;
  mcpTargetPath: string;
  mcpContent: string;
  portableItems: string[];
}

export async function exportCommand(): Promise<void> {
  const manifest = loadManifest();
  if (!manifest) return;

  const mcpPath = path.join(manifest.repoDir, "mcp.json");

  let config;
  try {
    config = parseMCPConfig(mcpPath);
  } catch (err) {
    error(`Failed to parse mcp.json: ${(err as Error).message}`);
    return;
  }

  const mcpRaw = fs.readFileSync(mcpPath, "utf-8");

  const enabledIds = Object.entries(manifest.agents)
    .filter(([, v]) => v.enabled)
    .map(([id]) => id);

  if (enabledIds.length === 0) {
    warn("No agents enabled in agentsync.json");
    return;
  }

  const agents: AgentExportInfo[] = [];

  for (const id of enabledIds) {
    const agentDef = loadAgentById(id);
    if (!agentDef) {
      warn(`Agent "${id}" in manifest but no definition found — skipping`);
      continue;
    }

    const result = transformForAgent(config, agentDef);
    const configDir = expandPath(getPlatformPath(agentDef.configDir));
    const mcpTargetPath = path.join(configDir, agentDef.mcp.configPath);

    let serialized: string;
    if (result.format === "toml") {
      serialized = TOML.stringify({ [result.rootKey]: result.servers }) + "\n";
    } else {
      serialized =
        JSON.stringify({ [result.rootKey]: result.servers }, null, 2) + "\n";
    }

    agents.push({
      agentDef,
      configDir,
      mcpTargetPath,
      mcpContent: serialized,
      portableItems: getPortableItems(agentDef),
    });
  }

  const script = generateExportScript(manifest.repoDir, mcpRaw, agents);
  process.stdout.write(script);
}

/**
 * Replace the user's home directory with $HOME for portability.
 * Normalizes backslashes to forward slashes for Windows compatibility.
 */
function makePortablePath(p: string): string {
  const normalized = p.replace(/\\/g, "/");
  const home = os.homedir().replace(/\\/g, "/");
  if (normalized.startsWith(home + "/") || normalized === home) {
    return "$HOME" + normalized.slice(home.length);
  }
  return normalized;
}

/**
 * Generate a heredoc delimiter that does not collide with the content.
 */
function safeDelimiter(base: string, content: string): string {
  let delimiter = base;
  while (
    content.includes(`\n${delimiter}\n`) ||
    content.startsWith(`${delimiter}\n`) ||
    content.endsWith(`\n${delimiter}`)
  ) {
    delimiter = `${base}_${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
  }
  return delimiter;
}

/**
 * Generate the self-contained bash install script.
 * Exported for testability.
 */
export function generateExportScript(
  repoDir: string,
  mcpRaw: string,
  agents: AgentExportInfo[],
): string {
  const lines: string[] = [];

  lines.push("#!/bin/bash");
  lines.push("# Generated by agentsync export");
  lines.push(
    "# Sets up agent configs without requiring agentsync to be installed.",
  );
  lines.push("# Usage: bash install.sh");
  lines.push("");
  lines.push("set -euo pipefail");
  lines.push("");

  // Repo dir variable
  const portableRepoDir = makePortablePath(repoDir);
  lines.push(`REPO_DIR="${portableRepoDir}"`);
  lines.push("");

  // Create repo directory structure
  lines.push("# Create config repo directory structure");
  lines.push('mkdir -p "$REPO_DIR"');
  for (const agent of agents) {
    lines.push(`mkdir -p "$REPO_DIR/${agent.agentDef.id}"`);
  }
  lines.push("");

  // Write mcp.json
  const mcpDelimiter = safeDelimiter("AGENTSYNC_MCP_EOF", mcpRaw);
  lines.push("# Write normalized mcp.json");
  lines.push(`cat > "$REPO_DIR/mcp.json" << '${mcpDelimiter}'`);
  lines.push(mcpRaw.trimEnd());
  lines.push(mcpDelimiter);
  lines.push("");

  // Per-agent sections
  for (const agent of agents) {
    const eofBase = `AGENTSYNC_EOF_${agent.agentDef.id.toUpperCase().replace(/-/g, "_")}`;
    const eof = safeDelimiter(eofBase, agent.mcpContent);
    const portableConfigDir = makePortablePath(agent.configDir);
    const portableMcpTarget = makePortablePath(agent.mcpTargetPath);

    lines.push(`# --- ${agent.agentDef.name} ---`);
    lines.push(`AGENT_CONFIG_DIR="${portableConfigDir}"`);
    lines.push('mkdir -p "$AGENT_CONFIG_DIR"');
    lines.push("");

    // Write MCP config
    lines.push(`cat > "${portableMcpTarget}" << '${eof}'`);
    lines.push(agent.mcpContent.trimEnd());
    lines.push(eof);
    lines.push("");

    // Create symlinks for portable files
    if (agent.portableItems.length > 0) {
      lines.push(`# Symlinks for ${agent.agentDef.name}`);
      for (const item of agent.portableItems) {
        lines.push(
          `if [ -e "$REPO_DIR/${agent.agentDef.id}/${item}" ]; then`,
        );
        lines.push(`  DEST="$AGENT_CONFIG_DIR/${item}"`);
        lines.push(`  SRC="$REPO_DIR/${agent.agentDef.id}/${item}"`);
        lines.push('  if [ -L "$DEST" ]; then');
        lines.push('    rm "$DEST"');
        lines.push('  elif [ -e "$DEST" ]; then');
        lines.push('    mv "$DEST" "$DEST.backup.$(date +%s)"');
        lines.push("  fi");
        lines.push('  ln -s "$SRC" "$DEST"');
        lines.push("fi");
      }
      lines.push("");
    }

    lines.push(`echo "Done: ${agent.agentDef.name}"`);
    lines.push("");
  }

  lines.push(`echo "${agents.length} agent(s) configured from $REPO_DIR"`);

  return lines.join("\n") + "\n";
}
